### ISSUE TITLE
Custom skill not being invoked

### ISSUE THREAD

**Issue by koshyviv** [richtier/alexa-voice-service-client#17]
I'm able to get responses for generic statements as - 
```
What is the time now
How is the weather
```

But I'm not able to use my custom skill. Any idea on how i can proceed?

Thanks for the amazing library though :)

**Comment by koshyviv** [comment]
I had a similar problem while trying with echoism.io, it was fixed after refreshing the page with the locale set to en-US.
Is there a similar setting here which i can adjust?

**Comment by richtier** [comment]
Thanks for the kind words :)

Good news is I'm able to trigger custom skills through this library, so the library can do what you need.

The amazon account you used to generate the refresh token with must have the custom skill enabled. I used the Alexa smartphone app to enable it. Perhaps that's the problem?

Can you quote the phrase you use to invoke the custom command please. E.g., I say "Edgar, call the front room" to triggers a custom command that results in a two way video chat between tablets running web apps I built using Alexa browser client.

https://youtu.be/cm19aa6x9VY
https://github.com/richtier/alexa-browser-client

**Comment by richtier** [comment]
I have a look on the code to check if I've hard-coded the locale. If so I'll add the ability to configure that.

**Comment by richtier** [comment]
Yes, the EU region is hard-coded.

https://github.com/richtier/alexa-voice-service-client/blob/master/avs_client/avs_client/connection.py#L12

The ability to configure is needed.

Here is a list of region endpoints:

https://developer.amazon.com/docs/alexa-voice-service/api-overview.html#endpoints

Feel free to make a pull request adding this feature. If your busy I'll add that over the next few days.

**Comment by koshyviv** [comment]
Thanks for looking up!

Its finally working for me, i did not have to modify the connections.py file. There was a similar issue mentioned - [Regarding Location settings in avs-device-sdk #711](https://github.com/alexa/avs-device-sdk/issues/711). Followed the steps there and it worked!

Since, from the link 

> The endpoint location is selected by the service automatically 

I think we can safely close this issue, since the cause is from the alexa services side
