### ISSUE TITLE
Possible to get the text transcript along with the audio file response?

### ISSUE THREAD

**Issue by koshyviv** [richtier/alexa-voice-service-client#20]
Any idea on what can be done to get the transcript?

**Comment by richtier** [comment]
@koshyviv I think this feature is unsupported by Alexa Voice Service. If you know otherwise please link to documentation and we can implement the feature :)

**Comment by koshyviv** [comment]
You're correct there is no documentation. I was able to find the transcripts from the history of alexa here -
https://alexa.amazon.com/spa/index.html#settings/dialogs

I can almost make good use of it. But for some reasons, i don't see the history being populated immediately for the requests that are sent from this client. For other services, like echoism it seems prompt.
Do you have an idea on this is so?

**Comment by richtier** [comment]
@koshyviv interesting. I wonder if it's because the http2 stream remains open. try updating [this](https://github.com/richtier/alexa-voice-service-client/blob/master/avs_client/avs_client/connection.py#L136) to something like:

```
        response = self.connection.get_response(stream_id)
        parsed = self.parse_response(response)
        response.close()
        return parsed
```

and feed back if the transcript becomes immedately available.

**Comment by richtier** [comment]
@koshyviv any movement on this?

**Comment by koshyviv** [comment]
@richtier i am assuming there was a server side issue -  since its working well now without the update

**Comment by richtier** [comment]
good stuff. Closing.
