### ISSUE TITLE
Add support for template runtime interface.

### ISSUE THREAD

**Issue by mushfiq** [richtier/alexa-voice-service-client#27]
Currently the project does not support [TemplateRuntime](https://developer.amazon.com/docs/alexa-voice-service/templateruntime.html) interface.

For devices where users want to display text and images the supports are needed.

**Comment by richtier** [comment]
@mushfiq what changes are needed to inform AVS that the device supports templates? I suspect it needs to be alerted to the fact the device has a screen.

**Comment by richtier** [comment]
Great. If it's that simple then we should be able to simply check `directive.name == 'RenderTemplate'. Can you test that and let me know.

**Comment by mushfiq** [comment]
@richtier I will check it and let you know soon.

**Comment by mushfiq** [comment]
Hi @richtier below is my findings:

```
elif directive.name == 'RenderTemplate':
        print(directive.directive)  # do something with directive template data
```
Does not work out of the box. 
As the _avs_client_ implementation looks only for octet-stream  and it filters out other content type. To overcome that, the current (tested on _1.0.1_) implementation needs to be adjusted. 

BTW, sorry for late feedback :)

**Comment by mushfiq** [comment]
@richtier as prerequisite the display card options should be enabled from the product settings.

AVS does not provide **RenderTemplate** out of the box, for some queries it has template data for some it does not. 
I am also planning to implement it (but not sure when exactly I will be done with that). If I can finish soon, I will submit a PR.

**Comment by mushfiq** [comment]
Hi @richtier I tried the latest version of the client and now RenderTemplate directive is being returned via the client.  I am closing this issue. The RenderTemplate payload can be accessed like below:

``` directive.directive.get("payload")```
