### ISSUE TITLE
Add support for initiator in ExpectSpeech directive.

### ISSUE THREAD

**Issue by mushfiq** [richtier/alexa-voice-service-client#34]
Currently during the multi-turn requests, the AVS client is not sending `initiator`.

But for supporting multi-turn AVS expects `initiator` (when it's being send with previous AVS response).

From AVS documentation

> If present, the initiator object included in the payload of the ExpectSpeech directive must be passed back to Alexa as the initiator object in the following Recognize event. If initiator is absent from the payload, the following Recognize event should not include initiator.

Details can be found here https://developer.amazon.com/docs/alexa-voice-service/speechrecognizer.html#expectspeech

**Comment by richtier** [comment]
thanks. I plan to add this over the next week

**Comment by richtier** [comment]
I finally had a look at implementing this.

Unfortunately AVS assumes the if a wakeword was used, that wakeworld will always be "Alexa". One of the perks of `alexa-client` is the ability to customize the wakeword. AVS would push a directive telling us the audio sent to AVS did not contain the _Alexa_ wakeword, which would be true but not helpful :)

https://developer.amazon.com/docs/alexa-voice-service/speechrecognizer.html#recognize

> initiator.payload.wakeWord | The wake word that woke the device, in all capital letters. Accepted Values: ALEXA

I therefore do not see a compelling case to implement this feature
