### ISSUE TITLE
send text to avs

### ISSUE THREAD

**Issue by mduzgun** [richtier/alexa-voice-service-client#35]
How to send text to Alexa instead of audio file? Is there any way?

**Comment by richtier** [comment]
Not that I am aware of. You can, however, send the text to a text to speech service then send hte resulting audio to alexa voice service using this client:

1. https://console.aws.amazon.com/polly/home/SynthesizeSpeech (select MP3 16000Hz)
2. convert it to wav: `$ffmpeg -i input.mp3 -ar 16000 output.wav`
3. Upload the AVS using this library
