### ISSUE TITLE
get text from AVS

### ISSUE THREAD

**Issue by mduzgun** [richtier/alexa-voice-service-client#36]
How to get response as a text from Alexa ?

**Comment by richtier** [comment]
you would need to set up a [custom skill](https://developer.amazon.com/docs/custom-skills/understanding-custom-skills.html)

So you may say "ask <my custom skill name> to do <whatever you want>"

alexa voice service will then post the text intent/meaning to the API endpoint you specify.

Your skill can then perform whatever action you want based on the intent/meaning

**Comment by DanBmh** [comment]
https://github.com/richtier/alexa-voice-service-client/issues/47#issuecomment-625979745
