### ISSUE TITLE
Client could not install

### ISSUE THREAD

**Issue by guanw** [richtier/alexa-voice-service-client#37]
Hi, I'm seeing same error as #26. The python version is 2.7.9.

![image](https://user-images.githubusercontent.com/7311035/58747937-ddc51e80-843f-11e9-8649-fd1216903057.png)

**Comment by richtier** [comment]
your python version is not supported. At the time of writing, [only python 3.5 and 3.6 are supported](https://github.com/richtier/alexa-voice-service-client/blob/master/setup.py#L48)
