### ISSUE TITLE
assert response.status in [http.client.NO_CONTENT, http.client.OK] AssertionError

### ISSUE THREAD

**Issue by gamerrio** [richtier/alexa-voice-service-client#38]
I am pretty sure I did all steps right 
still i am getting this error
Traceback (most recent call last):
  File "alexa.py", line 8, in <module>
    client.connect()  # authenticate and other handshaking steps
  File "C:\Users\Harshit.dell-PC\AppData\Local\Programs\Python\Python36\lib\site-packages\alexa_client\alexa_client\client.py", line 33, in connect
    self.synchronise_device_state()
  File "C:\Users\Harshit.dell-PC\AppData\Local\Programs\Python\Python36\lib\site-packages\alexa_client\alexa_client\client.py", line 49, in synchronise_device_state
    device_state=self.device_manager.get_device_state(),
  File "C:\Users\Harshit.dell-PC\AppData\Local\Programs\Python\Python36\lib\site-packages\alexa_client\alexa_client\connection.py", line 74, in synchronise_device_state
    assert response.status in [http.client.NO_CONTENT, http.client.OK]
AssertionError

**Comment by fredericlepoutreTL** [comment]
Hi guys,

I have the exact same problem.
It used to work fine a few weeks ago, and now it doesn't. I suspect something has changed at Alexa.

Any solution?

Thanks!
Fred

**Comment by parasgarg-smms** [comment]
Same Issue i m getting with AlexaClient, pretty sure about the whole procedure
Sometimes i even get the run time error but due to the access_token used in place of refresh_token

**Comment by pythonimus** [comment]
I also get the same error. It semms like the library is broken.

**Comment by pythonimus** [comment]
> 
> 
> Same problem!
> The response is 405: METHOD_NOT_ALLOWED
> However, I haven't found any change in Alexa Voice Service https://developer.amazon.com/docs/alexa-voice-service/system.html#synchronizestate .
> 
> Any solution right now?
> Thanks!
> 
> Fix it! I add 'http.client.METHOD_NOT_ALLOWED', it works.

I think this does not fix the problem at all.
I think it is because the library tries to GET the syncronizestate, whereas it should POST it. Just exchange GET with POST and it works.

**Comment by Samsonsjarkal** [comment]
> > Same problem!
> > The response is 405: METHOD_NOT_ALLOWED
> > However, I haven't found any change in Alexa Voice Service https://developer.amazon.com/docs/alexa-voice-service/system.html#synchronizestate .
> > Any solution right now?
> > Thanks!
> > Fix it! I add 'http.client.METHOD_NOT_ALLOWED', it works.
> 
> I think this does not fix the problem at all.
> I think it is because the library tries to GET the syncronizestate, whereas it should POST it. Just exchange GET with POST and it works.

I see. Thank you!

**Comment by richtier** [comment]
[This has now been fixed](https://github.com/richtier/alexa-voice-service-client/pull/39)

Please install `alexa_client==1.4.1`
