### ISSUE TITLE
Hello, I got the authentication code but when i use the authentication code to fetch the access token i get 400 Client Error: Bad Request for url: https://api.amazon.com/auth/o2/token. Is there anything missing.

### ISSUE THREAD

**Issue by s1782662** [richtier/alexa-voice-service-client#40]
Hello, I got the authentication code but when i use the authentication code to fetch the access token i get 400 Client Error: Bad Request for url: https://api.amazon.com/auth/o2/token. DId i miss anything ?.

_Originally posted by @s1782662 in https://github.com/richtier/alexa-voice-service-client/issues/21#issuecomment-549024327_

**Comment by richtier** [comment]
have you followed this section of the readme? https://github.com/richtier/alexa-voice-service-client#authentication

try [rubber duck debugging](https://rubberduckdebugging.com/) your code against that section of the readme

**Comment by richtier** [comment]
closed due to inactivity. please reopen if this is still an issue
