### ISSUE TITLE
Host name should be input parameter

### ISSUE THREAD

**Issue by SivakumarBalu** [richtier/alexa-voice-service-client#41]
Currently, host is hardcoded to old legacy url 'avs-alexa-eu.amazon.com'. AVS enforcing to use specific region Base URLs [https://developer.amazon.com/docs/alexa-voice-service/api-overview.html#endpoints](url). For example, my client expected be connected with host North America Host Base URLs. 

if the Host url is input parameter along with client id, secret and refresh_token, then it will useful to your package as it is instead of forking a copy.

**Comment by richtier** [comment]
the supported way to do this is:

```
class ConnectionManager(alexa_client.connection.ConnectionManager):
    host = ...

class AlexaClient(alexa_client.AlexaClient):
    connection_manager_class = connection.ConnectionManager
```

adding `host` as a first class citizen paramater is indeed a good idea. I'll get on this soon

**Comment by richtier** [comment]
you can now set the `base_url` when instantiating the client:
```
from alexa_client.alexa_client import constants

client = AlexaClient(
    client_id='my-client-id',
    secret='my-secret',
    refresh_token='my-refresh-token',
    base_url=constants.BASE_URL_ASIA
)
```
[read more](https://github.com/richtier/alexa-voice-service-client#base-url)

**Comment by SivakumarBalu** [comment]
Thanks for fixing on short span!
