### ISSUE TITLE
Client.send_audio_file returning None

### ISSUE THREAD

**Issue by z404** [richtier/alexa-voice-service-client#43]
When running the sample code given in the readme, i get the following error:
`Traceback (most recent call last):
  File "/root/Desktop/python/Project-Mark/trial.py", line 12, in <module>
    for i, directive in enumerate(client.send_audio_file(f)):
TypeError: 'NoneType' object is not iterable`

**Comment by z404** [comment]
My mistake. I had called the function twice.
I'm so sorry for raising this issue.

**Comment by 1337Phantom** [comment]
I have the same issue this is my code

`from alexa_client import AlexaClient
import speech_recognition as sr
import io
import pyaudio
from os import path
from pydub import AudioSegment

client = AlexaClient(
    client_id="XXXX",
    secret="XXXX",
    refresh_token="XXXX",
)
fileName = ''

p = pyaudio.PyAudio()
r = sr.Recognizer()

def callback(in_data, frame_count, time_info, status):
    buffer.write(in_data)
    return (in_data, pyaudio.paContinue)

stream = p.open(
    format=pyaudio.paInt16,
    channels=1,
    rate=44100,
    input=True,
    stream_callback=callback,
)

buffer = io.BytesIO()
print("err")
client.connect()
try:
    stream.start_stream()
    print('Listening... Press CTRL + C to exit.')    
    if(type(buffer) != None):
        asb = client.send_audio_file(buffer)
        for i, directive in enumerate(asb):
            if directive.name in ['Speak', 'Play']:
                src = "output_{}.mp3".format(i)
                with open(f'./output_{i}.mp3', 'wb') as f:
                    f.write(directive.audio_attachment)
finally:
    print('Recording Stopped')
    stream.stop_stream()
    stream.close()
    p.terminate()
`
