### ISSUE TITLE
Text response from AVS

### ISSUE THREAD

**Issue by kartikeya-rana** [richtier/alexa-voice-service-client#47]
Hi,

As per the following example of yours, the response is stored as an mp3 file. I want text as a response. How can I get that ? 

**with open('./tests/resources/alexa_what_time_is_it.wav', 'rb') as f:
    resp = client.send_audio_file(f)
    for i, directive in enumerate(resp):
        if directive.name in ['Speak', 'Play']:
            with open(f'./output_{i}.mp3', 'wb') as f:
                f.write(directive.audio_attachment)**

**Comment by DanBmh** [comment]
You will have to create a custom alexa skill.

There you can return your text with a card object like this:
```
return (
            handler_input.response_builder
                .speak(speak_output)
                .ask(speak_output)
                .set_card(SimpleCard("card_title", "your_card_text"))
                .response
        )
```

Then you can get your text with:
```
response = client.send_audio_file(file)
for i, res in enumerate(response):
    if res.name == "RenderTemplate":
        your_card_text = res.directive["payload"]["textField"]
```
