### ISSUE TITLE
Can't get payload when request using file - 'Directive' object is not subscriptable

### ISSUE THREAD

**Issue by mhilmiasyrofi** [richtier/alexa-voice-service-client#49]
Environment :
Python 3.6.9 on Ubuntu 16.04

I think this bug related to multipart from request. For each request I get the header name, but the payload is missing. When I print the whole directive response, it shows the payload but the Directive class can't get it

`
{'header': {'dialogRequestId': '....',
            'messageId': ....
            'name': 'RenderTemplate',
            'namespace': 'TemplateRuntime'},
 'payload': {'skillIcon': ......
             'textField': 'this',
             'title': {'mainTitle': 'Transcription',
                       'subTitle': 'Transcribe Test'},
             'token':....',
             'type': 'BodyTemplate1'}}
`

Seems the Alexa return the payload, but the directive class can't get it

**Comment by richtier** [comment]
hello,

Apologies about the late response.

The reason this is happening is this library does not have full support for all the directive types. Currently it only supports Speak, Play, and ExpectSpeech. But good news it it would be easy to add support to RenderTemplate:

https://github.com/richtier/alexa-voice-service-client/blob/61b72766d9a745a96fd1560aec7c4164cea8e4a3/alexa_client/alexa_client/helpers.py#L123

```
elif name == 'RenderTemplate':
    yield RenderTemplateDirective.from_multipart(
        part, audio_attachments=audio_attachments
     )
```

you would of course need to also add `RenderTemplateDirective` here: https://github.com/richtier/alexa-voice-service-client/blob/master/alexa_client/alexa_client/helpers.py

**Comment by richtier** [comment]
closing as I think my reply covers the issue
